export type SalesBudgetChartAvailability =
  | "available_now"
  | "needs_mapping"
  | "needs_new_view";

export type SalesBudgetChartPreview = {
  id: string;
  title: string;
  availability: SalesBudgetChartAvailability;
};

export type SalesBudgetCategoryPreview = {
  id: string;
  name: string;
  description: string;
  plannedCount: number;
  availableNowCount: number;
  needsNewViewCount: number;
  highlights: SalesBudgetChartPreview[];
};

export const salesBudgetCatalog: SalesBudgetCategoryPreview[] = [
  {
    id: "overview",
    name: "Visão geral",
    description: "Panorama inicial de orçamentos, volume, ticket médio e sazonalidade.",
    plannedCount: 15,
    availableNowCount: 15,
    needsNewViewCount: 0,
    highlights: [
      { id: "overview_total_amount_period", title: "Valor total de orçamentos por período", availability: "available_now" },
      { id: "overview_total_count_period", title: "Quantidade de orçamentos por período", availability: "available_now" },
      { id: "overview_avg_ticket", title: "Ticket médio dos orçamentos", availability: "available_now" },
      { id: "overview_amount_by_company", title: "Valor total por empresa/filial", availability: "available_now" },
      { id: "overview_count_by_company", title: "Quantidade de orçamentos por empresa/filial", availability: "available_now" },
      { id: "overview_monthly_evolution", title: "Evolução mensal de orçamentos", availability: "available_now" },
      { id: "overview_weekly_evolution", title: "Evolução semanal de orçamentos", availability: "available_now" },
      { id: "overview_daily_evolution", title: "Evolução diária de orçamentos", availability: "available_now" },
      { id: "overview_current_vs_previous_month", title: "Comparativo mês atual x mês anterior", availability: "available_now" },
      { id: "overview_current_year_vs_previous_year", title: "Comparativo ano atual x ano anterior", availability: "available_now" },
      { id: "overview_top_days_by_volume", title: "Top dias com maior volume de orçamentos", availability: "available_now" },
      { id: "overview_top_months_by_amount", title: "Top meses com maior valor orçado", availability: "available_now" },
      { id: "overview_month_seasonality", title: "Sazonalidade de vendas/orçamentos por mês", availability: "available_now" },
      { id: "overview_weekday_heatmap", title: "Mapa de calor por dia da semana", availability: "available_now" },
      { id: "overview_month_year_heatmap", title: "Mapa de calor por mês e ano", availability: "available_now" },
    ],
  },
  {
    id: "funnel",
    name: "Funil comercial",
    description: "Status, conversão, perdas e gargalos do funil de orçamentos.",
    plannedCount: 15,
    availableNowCount: 7,
    needsNewViewCount: 0,
    highlights: [
      { id: "funnel_by_status", title: "Funil por status do orçamento", availability: "available_now" },
      { id: "funnel_amount_by_status", title: "Valor total por status", availability: "available_now" },
      { id: "funnel_count_by_status", title: "Quantidade de orçamentos por status", availability: "available_now" },
      { id: "funnel_conversion_percent_by_status", title: "Percentual de conversão por status", availability: "available_now" },
      { id: "funnel_open_approved_lost", title: "Orçamentos em aberto x aprovados x perdidos", availability: "available_now" },
      { id: "funnel_pending_amount", title: "Valor parado em orçamentos pendentes", availability: "available_now" },
      { id: "funnel_approval_rate", title: "Taxa de aprovação de orçamentos", availability: "needs_mapping" },
      { id: "funnel_loss_cancel_rate", title: "Taxa de perda/cancelamento", availability: "needs_mapping" },
      { id: "funnel_conversion_evolution", title: "Evolução da conversão ao longo do tempo", availability: "needs_mapping" },
      { id: "funnel_conversion_by_seller", title: "Conversão por vendedor", availability: "needs_mapping" },
      { id: "funnel_conversion_by_customer", title: "Conversão por cliente", availability: "needs_mapping" },
      { id: "funnel_conversion_by_origin", title: "Conversão por origem", availability: "needs_mapping" },
      { id: "funnel_conversion_by_geo", title: "Conversão por cidade/UF", availability: "needs_mapping" },
      { id: "funnel_conversion_by_payment", title: "Conversão por condição de pagamento", availability: "needs_mapping" },
      { id: "funnel_blocking_status_ranking", title: "Ranking de status que mais travam vendas", availability: "available_now" },
    ],
  },
  {
    id: "seller",
    name: "Vendedores",
    description: "Performance comercial, ranking, markup, desconto e evolução por vendedor.",
    plannedCount: 20,
    availableNowCount: 17,
    needsNewViewCount: 0,
    highlights: [
      { id: "seller_total_amount", title: "Valor total orçado por vendedor", availability: "available_now" },
      { id: "seller_total_count", title: "Quantidade de orçamentos por vendedor", availability: "available_now" },
      { id: "seller_avg_ticket", title: "Ticket médio por vendedor", availability: "available_now" },
      { id: "seller_conversion", title: "Conversão por vendedor", availability: "needs_mapping" },
      { id: "seller_avg_discount", title: "Desconto médio concedido por vendedor", availability: "available_now" },
      { id: "seller_avg_markup", title: "Markup médio por vendedor", availability: "available_now" },
      { id: "seller_avg_surcharge", title: "Acréscimo médio por vendedor", availability: "available_now" },
      { id: "seller_avg_freight", title: "Valor de frete médio por vendedor", availability: "available_now" },
      { id: "seller_ranking_amount", title: "Ranking de vendedores por valor total", availability: "available_now" },
      { id: "seller_ranking_count", title: "Ranking de vendedores por quantidade", availability: "available_now" },
      { id: "seller_ranking_ticket", title: "Ranking de vendedores por ticket médio", availability: "available_now" },
      { id: "seller_ranking_markup", title: "Ranking de vendedores por margem/markup", availability: "available_now" },
      { id: "seller_most_lost", title: "Vendedores com mais orçamentos perdidos", availability: "needs_mapping" },
      { id: "seller_most_approved", title: "Vendedores com mais orçamentos aprovados", availability: "needs_mapping" },
      { id: "seller_monthly_evolution", title: "Evolução mensal por vendedor", availability: "available_now" },
      { id: "seller_comparison", title: "Comparativo entre vendedores", availability: "available_now" },
      { id: "seller_share_total", title: "Participação de cada vendedor no faturamento", availability: "available_now" },
      { id: "seller_abc_curve", title: "Curva ABC de vendedores", availability: "available_now" },
      { id: "seller_top_product", title: "Vendedor x produto mais orçado", availability: "available_now" },
      { id: "seller_top_customer", title: "Vendedor x cliente mais atendido", availability: "available_now" },
    ],
  },
  {
    id: "customer",
    name: "Clientes",
    description: "Ticket, recorrência, conversão, origem e distribuição geográfica dos clientes.",
    plannedCount: 20,
    availableNowCount: 18,
    needsNewViewCount: 0,
    highlights: [
      { id: "customer_top_amount", title: "Top clientes por valor orçado", availability: "available_now" },
      { id: "customer_top_count", title: "Top clientes por quantidade de orçamentos", availability: "available_now" },
      { id: "customer_avg_ticket", title: "Ticket médio por cliente", availability: "available_now" },
      { id: "customer_recurring", title: "Clientes recorrentes", availability: "available_now" },
      { id: "customer_new_period", title: "Clientes novos por período", availability: "available_now" },
      { id: "customer_inactive_recent", title: "Clientes sem orçamento recente", availability: "available_now" },
      { id: "customer_highest_discount", title: "Clientes com maior desconto recebido", availability: "available_now" },
      { id: "customer_highest_markup", title: "Clientes com maior markup", availability: "available_now" },
      { id: "customer_highest_open_amount", title: "Clientes com maior valor em aberto", availability: "available_now" },
      { id: "customer_highest_conversion", title: "Clientes com maior taxa de conversão", availability: "needs_mapping" },
      { id: "customer_low_conversion", title: "Clientes com baixa conversão", availability: "needs_mapping" },
      { id: "customer_abc_curve", title: "Curva ABC de clientes", availability: "available_now" },
      { id: "customer_top_share", title: "Participação dos principais clientes no total", availability: "available_now" },
      { id: "customer_evolution", title: "Evolução de orçamentos por cliente", availability: "available_now" },
      { id: "customer_top_products", title: "Cliente x produtos mais orçados", availability: "available_now" },
      { id: "customer_responsible_seller", title: "Cliente x vendedor responsável", availability: "available_now" },
      { id: "customer_origin", title: "Cliente x origem", availability: "available_now" },
      { id: "customer_payment_condition", title: "Cliente x condição de pagamento", availability: "available_now" },
      { id: "customer_by_city", title: "Clientes por cidade", availability: "available_now" },
      { id: "customer_by_uf", title: "Clientes por UF", availability: "available_now" },
    ],
  },
  {
    id: "product",
    name: "Produtos",
    description: "Itens orçados, demanda, valor unitário, mix e associação entre produtos.",
    plannedCount: 25,
    availableNowCount: 25,
    needsNewViewCount: 0,
    highlights: [
      { id: "product_top_amount", title: "Top produtos por valor total", availability: "available_now" },
      { id: "product_top_quantity", title: "Top produtos por quantidade orçada", availability: "available_now" },
      { id: "product_highest_avg_ticket", title: "Produtos com maior ticket médio", availability: "available_now" },
      { id: "product_highest_discount", title: "Produtos com maior desconto aplicado", availability: "available_now" },
      { id: "product_highest_markup", title: "Produtos com maior markup", availability: "available_now" },
      { id: "product_highest_surcharge", title: "Produtos com maior acréscimo", availability: "available_now" },
      { id: "product_most_quoted_period", title: "Produtos mais orçados por período", availability: "available_now" },
      { id: "product_least_quoted", title: "Produtos menos orçados", availability: "available_now" },
      { id: "product_demand_drop", title: "Produtos com queda de demanda", availability: "available_now" },
      { id: "product_demand_growth", title: "Produtos com crescimento de demanda", availability: "available_now" },
      { id: "product_monthly_evolution", title: "Evolução mensal por produto", availability: "available_now" },
      { id: "product_abc_curve", title: "Curva ABC de produtos", availability: "available_now" },
      { id: "product_share_total", title: "Participação dos produtos no valor total", availability: "available_now" },
      { id: "product_by_seller", title: "Produtos por vendedor", availability: "available_now" },
      { id: "product_by_customer", title: "Produtos por cliente", availability: "available_now" },
      { id: "product_by_geo", title: "Produtos por cidade/UF", availability: "available_now" },
      { id: "product_by_company", title: "Produtos por empresa/filial", availability: "available_now" },
      { id: "product_by_origin", title: "Produtos por origem do orçamento", availability: "available_now" },
      { id: "product_highest_gross_unit", title: "Produtos com maior valor unitário bruto", availability: "available_now" },
      { id: "product_highest_net_unit", title: "Produtos com maior valor unitário líquido", availability: "available_now" },
      { id: "product_gross_net_gap", title: "Diferença entre valor bruto e líquido", availability: "available_now" },
      { id: "product_avg_quantity_per_item", title: "Quantidade média por item", availability: "available_now" },
      { id: "product_avg_value_per_item", title: "Valor médio por item", availability: "available_now" },
      { id: "product_mix_per_budget", title: "Mix de produtos por orçamento", availability: "available_now" },
      { id: "product_cooccurrence", title: "Produtos que mais aparecem juntos", availability: "available_now" },
    ],
  },
  {
    id: "margin",
    name: "Descontos e margem",
    description: "Desconto, acréscimo, markup e orçamentos com possível margem ruim.",
    plannedCount: 25,
    availableNowCount: 24,
    needsNewViewCount: 0,
    highlights: [
      { id: "margin_total_discount", title: "Valor total de descontos concedidos", availability: "available_now" },
      { id: "margin_avg_discount_percent", title: "Percentual médio de desconto", availability: "available_now" },
      { id: "margin_discount_by_seller", title: "Desconto por vendedor", availability: "available_now" },
      { id: "margin_discount_by_customer", title: "Desconto por cliente", availability: "available_now" },
      { id: "margin_discount_by_product", title: "Desconto por produto", availability: "available_now" },
      { id: "margin_discount_by_origin", title: "Desconto por origem", availability: "available_now" },
      { id: "margin_discount_by_payment", title: "Desconto por condição de pagamento", availability: "available_now" },
      { id: "margin_highest_discount_ranking", title: "Ranking de maiores descontos", availability: "available_now" },
      { id: "margin_above_avg_discount_budgets", title: "Orçamentos com desconto acima da média", availability: "available_now" },
      { id: "margin_discount_impact_total", title: "Impacto do desconto no valor total", availability: "available_now" },
      { id: "margin_discount_vs_conversion", title: "Relação desconto x conversão", availability: "needs_mapping" },
      { id: "margin_discount_vs_seller", title: "Relação desconto x vendedor", availability: "available_now" },
      { id: "margin_total_surcharge", title: "Valor total de acréscimos", availability: "available_now" },
      { id: "margin_avg_surcharge_percent", title: "Percentual médio de acréscimo", availability: "available_now" },
      { id: "margin_surcharge_by_seller", title: "Acréscimo por vendedor", availability: "available_now" },
      { id: "margin_surcharge_by_customer", title: "Acréscimo por cliente", availability: "available_now" },
      { id: "margin_surcharge_by_product", title: "Acréscimo por produto", availability: "available_now" },
      { id: "margin_avg_markup_general", title: "Markup médio geral", availability: "available_now" },
      { id: "margin_markup_by_seller", title: "Markup por vendedor", availability: "available_now" },
      { id: "margin_markup_by_product", title: "Markup por produto", availability: "available_now" },
      { id: "margin_markup_by_customer", title: "Markup por cliente", availability: "available_now" },
      { id: "margin_markup_by_origin", title: "Markup por origem", availability: "available_now" },
      { id: "margin_low_markup_budgets", title: "Orçamentos com markup baixo", availability: "available_now" },
      { id: "margin_possible_bad_margin_budgets", title: "Orçamentos com possível margem ruim", availability: "available_now" },
      { id: "margin_gross_vs_net", title: "Comparativo valor bruto x valor líquido", availability: "available_now" },
    ],
  },
  {
    id: "source",
    name: "Origem",
    description: "Canais de venda, participação, ticket e conversão por origem.",
    plannedCount: 15,
    availableNowCount: 13,
    needsNewViewCount: 0,
    highlights: [
      { id: "source_total_amount", title: "Valor total por origem", availability: "available_now" },
      { id: "source_total_count", title: "Quantidade de orçamentos por origem", availability: "available_now" },
      { id: "source_avg_ticket", title: "Ticket médio por origem", availability: "available_now" },
      { id: "source_conversion", title: "Conversão por origem", availability: "needs_mapping" },
      { id: "source_highest_avg_discount", title: "Origem com maior desconto médio", availability: "available_now" },
      { id: "source_highest_markup", title: "Origem com maior markup", availability: "available_now" },
      { id: "source_evolution", title: "Evolução de origens por período", availability: "available_now" },
      { id: "source_share_total", title: "Participação de cada origem no total", availability: "available_now" },
      { id: "source_by_seller", title: "Origem x vendedor", availability: "available_now" },
      { id: "source_by_product", title: "Origem x produto", availability: "available_now" },
      { id: "source_by_customer", title: "Origem x cliente", availability: "available_now" },
      { id: "source_by_geo", title: "Origem x cidade/UF", availability: "available_now" },
      { id: "source_best_channels", title: "Ranking de melhores canais de venda", availability: "available_now" },
      { id: "source_high_volume_low_conversion", title: "Canais com muito orçamento e pouca conversão", availability: "needs_mapping" },
      { id: "source_low_volume_high_ticket", title: "Canais com menos volume, mas maior ticket", availability: "available_now" },
    ],
  },
  {
    id: "geo",
    name: "Geografia",
    description: "Distribuição por UF, cidade, região, vendedor e oportunidade geográfica.",
    plannedCount: 17,
    availableNowCount: 16,
    needsNewViewCount: 0,
    highlights: [
      { id: "geo_amount_by_uf", title: "Valor total por UF", availability: "available_now" },
      { id: "geo_count_by_uf", title: "Quantidade de orçamentos por UF", availability: "available_now" },
      { id: "geo_avg_ticket_by_uf", title: "Ticket médio por UF", availability: "available_now" },
      { id: "geo_conversion_by_uf", title: "Conversão por UF", availability: "needs_mapping" },
      { id: "geo_amount_by_city", title: "Valor total por cidade", availability: "available_now" },
      { id: "geo_count_by_city", title: "Quantidade por cidade", availability: "available_now" },
      { id: "geo_top_cities_count", title: "Ranking de cidades com mais orçamentos", availability: "available_now" },
      { id: "geo_top_cities_ticket", title: "Ranking de cidades com maior ticket médio", availability: "available_now" },
      { id: "geo_state_heatmap", title: "Mapa de calor por estado", availability: "available_now" },
      { id: "geo_city_heatmap", title: "Mapa de calor por cidade", availability: "available_now" },
      { id: "geo_seller_by_region", title: "Vendedor por região", availability: "available_now" },
      { id: "geo_top_product_by_uf", title: "Produto mais orçado por UF", availability: "available_now" },
      { id: "geo_customer_by_region", title: "Cliente por região", availability: "available_now" },
      { id: "geo_origin_by_region", title: "Origem por região", availability: "available_now" },
      { id: "geo_highest_avg_discount_regions", title: "Regiões com maior desconto médio", availability: "available_now" },
      { id: "geo_highest_markup_regions", title: "Regiões com maior markup", availability: "available_now" },
      { id: "geo_growth_opportunity_regions", title: "Regiões com maior oportunidade de crescimento", availability: "available_now" },
    ],
  },
  {
    id: "payment",
    name: "Condição de pagamento",
    description: "Uso, ticket, desconto, markup e aprovação por condição de pagamento.",
    plannedCount: 12,
    availableNowCount: 10,
    needsNewViewCount: 0,
    highlights: [
      { id: "payment_total_amount", title: "Valor total por condição de pagamento", availability: "available_now" },
      { id: "payment_total_count", title: "Quantidade por condição de pagamento", availability: "available_now" },
      { id: "payment_avg_ticket", title: "Ticket médio por condição de pagamento", availability: "available_now" },
      { id: "payment_conversion", title: "Conversão por condição de pagamento", availability: "needs_mapping" },
      { id: "payment_avg_discount", title: "Desconto médio por condição de pagamento", availability: "available_now" },
      { id: "payment_avg_markup", title: "Markup médio por condição de pagamento", availability: "available_now" },
      { id: "payment_most_used", title: "Condições de pagamento mais usadas", availability: "available_now" },
      { id: "payment_by_seller", title: "Condição de pagamento x vendedor", availability: "available_now" },
      { id: "payment_by_customer", title: "Condição de pagamento x cliente", availability: "available_now" },
      { id: "payment_by_product", title: "Condição de pagamento x produto", availability: "available_now" },
      { id: "payment_by_origin", title: "Condição de pagamento x origem", availability: "available_now" },
      { id: "payment_vs_approval", title: "Condição de pagamento x aprovação", availability: "needs_mapping" },
    ],
  },
  {
    id: "freight",
    name: "Frete",
    description: "Valor de frete, tipo, impacto no ticket e relação com conversão.",
    plannedCount: 11,
    availableNowCount: 10,
    needsNewViewCount: 0,
    highlights: [
      { id: "freight_total_amount", title: "Valor total de frete", availability: "available_now" },
      { id: "freight_avg_per_budget", title: "Frete médio por orçamento", availability: "available_now" },
      { id: "freight_by_seller", title: "Frete por vendedor", availability: "available_now" },
      { id: "freight_by_customer", title: "Frete por cliente", availability: "available_now" },
      { id: "freight_by_geo", title: "Frete por cidade/UF", availability: "available_now" },
      { id: "freight_by_type", title: "Frete por tipo de frete", availability: "available_now" },
      { id: "freight_ratio_total", title: "Frete em relação ao valor total", availability: "available_now" },
      { id: "freight_high_budgets", title: "Orçamentos com frete alto", availability: "available_now" },
      { id: "freight_vs_conversion", title: "Relação frete x conversão", availability: "needs_mapping" },
      { id: "freight_most_used_type", title: "Tipo de frete mais usado", availability: "available_now" },
      { id: "freight_avg_ticket_by_type", title: "Ticket médio por tipo de frete", availability: "available_now" },
    ],
  },
  {
    id: "executive",
    name: "Diretoria",
    description: "Indicadores consolidados, pipeline, alertas e leitura executiva de vendas.",
    plannedCount: 20,
    availableNowCount: 18,
    needsNewViewCount: 2,
    highlights: [
      { id: "exec_dashboard", title: "Dashboard executivo de vendas", availability: "available_now" },
      { id: "exec_total_revenue_budget", title: "Receita/orçamento total por período", availability: "available_now" },
      { id: "exec_goal_vs_actual", title: "Meta x realizado", availability: "needs_new_view" },
      { id: "exec_sales_forecast", title: "Forecast de vendas", availability: "needs_new_view" },
      { id: "exec_open_pipeline", title: "Pipeline comercial em aberto", availability: "available_now" },
      { id: "exec_opportunity_ranking", title: "Ranking de oportunidades", availability: "available_now" },
      { id: "exec_monthly_growth", title: "Evolução de crescimento mensal", availability: "available_now" },
      { id: "exec_seller_share", title: "Participação por vendedor", availability: "available_now" },
      { id: "exec_customer_share", title: "Participação por cliente", availability: "available_now" },
      { id: "exec_product_share", title: "Participação por produto", availability: "available_now" },
      { id: "exec_region_share", title: "Participação por região", availability: "available_now" },
      { id: "exec_origin_share", title: "Participação por origem", availability: "available_now" },
      { id: "exec_avg_markup", title: "Margem/markup médio consolidado", availability: "available_now" },
      { id: "exec_total_discount", title: "Desconto total concedido", availability: "available_now" },
      { id: "exec_lost_opportunities", title: "Oportunidades perdidas", availability: "available_now" },
      { id: "exec_negotiation_opportunities", title: "Oportunidades em negociação", availability: "available_now" },
      { id: "exec_strategic_customers", title: "Clientes estratégicos", availability: "available_now" },
      { id: "exec_strategic_products", title: "Produtos estratégicos", availability: "available_now" },
      { id: "exec_strategic_channels", title: "Canais estratégicos", availability: "available_now" },
      { id: "exec_sales_drop_alerts", title: "Alertas de queda de vendas", availability: "available_now" },
    ],
  },
  {
    id: "seller_insights",
    name: "Insights para vendedores",
    description: "Follow-up, potencial de recompra, comparativos e oportunidades individuais.",
    plannedCount: 20,
    availableNowCount: 20,
    needsNewViewCount: 0,
    highlights: [
      { id: "insight_customers_high_conversion_chance", title: "Clientes com maior chance de conversão", availability: "available_now" },
      { id: "insight_frequent_customers", title: "Clientes que orçam com frequência", availability: "available_now" },
      { id: "insight_customers_stopped_quoting", title: "Clientes que pararam de orçar", availability: "available_now" },
      { id: "insight_recommended_products_by_customer", title: "Produtos mais indicados por cliente", availability: "available_now" },
      { id: "insight_top_products_by_region", title: "Produtos mais vendidos por região", availability: "available_now" },
      { id: "insight_high_acceptance_products", title: "Produtos com maior aceitação", availability: "available_now" },
      { id: "insight_pending_followup_budgets", title: "Orçamentos pendentes de follow-up", availability: "available_now" },
      { id: "insight_old_open_budgets", title: "Orçamentos antigos ainda em aberto", availability: "available_now" },
      { id: "insight_high_value_no_return", title: "Orçamentos de alto valor sem retorno", availability: "available_now" },
      { id: "insight_high_ticket_customers", title: "Clientes com alto ticket médio", availability: "available_now" },
      { id: "insight_discount_sensitive_customers", title: "Clientes sensíveis a desconto", availability: "available_now" },
      { id: "insight_low_discount_customers", title: "Clientes que compram sem muito desconto", availability: "available_now" },
      { id: "insight_best_origin_by_seller", title: "Melhor origem para cada vendedor", availability: "available_now" },
      { id: "insight_best_product_by_seller", title: "Melhor produto para cada vendedor", availability: "available_now" },
      { id: "insight_best_region_by_seller", title: "Melhor região para cada vendedor", availability: "available_now" },
      { id: "insight_seller_vs_team_avg", title: "Comparativo do vendedor com a equipe", availability: "available_now" },
      { id: "insight_personal_seller_ranking", title: "Ranking pessoal do vendedor", availability: "available_now" },
      { id: "insight_individual_monthly_evolution", title: "Evolução mensal individual", availability: "available_now" },
      { id: "insight_underused_products_by_seller", title: "Produtos que o vendedor vende pouco", availability: "available_now" },
      { id: "insight_repurchase_potential_customers", title: "Clientes com potencial de recompra", availability: "available_now" },
    ],
  },
  {
    id: "future_data",
    name: "Novas informações",
    description: "Gráficos dependentes de pedido, faturamento, estoque, custo, metas e marketing.",
    plannedCount: 30,
    availableNowCount: 0,
    needsNewViewCount: 30,
    highlights: [
      { id: "future_budget_vs_sold", title: "Orçado x vendido/faturado", availability: "needs_new_view" },
      { id: "future_budget_converted_to_order", title: "Orçamento convertido em pedido", availability: "needs_new_view" },
      { id: "future_avg_conversion_time", title: "Tempo médio de conversão", availability: "needs_new_view" },
      { id: "future_issue_to_approval_time", title: "Tempo médio entre emissão e aprovação", availability: "needs_new_view" },
      { id: "future_loss_reason", title: "Motivo de perda do orçamento", availability: "needs_new_view" },
      { id: "future_cancel_reason", title: "Motivo de cancelamento", availability: "needs_new_view" },
      { id: "future_goal_by_seller", title: "Meta por vendedor", availability: "needs_new_view" },
      { id: "future_goal_by_company", title: "Meta por filial", availability: "needs_new_view" },
      { id: "future_goal_by_product", title: "Meta por produto", availability: "needs_new_view" },
      { id: "future_goal_by_region", title: "Meta por região", availability: "needs_new_view" },
      { id: "future_real_margin_by_product", title: "Margem real por produto", availability: "needs_new_view" },
      { id: "future_gross_profit", title: "Lucro bruto", availability: "needs_new_view" },
      { id: "future_cogs", title: "Custo do produto vendido", availability: "needs_new_view" },
      { id: "future_available_stock", title: "Estoque disponível", availability: "needs_new_view" },
      { id: "future_stockout", title: "Ruptura de estoque", availability: "needs_new_view" },
      { id: "future_no_stock_lost_sales", title: "Produtos sem estoque que perderam venda", availability: "needs_new_view" },
      { id: "future_inventory_turnover", title: "Giro de estoque", availability: "needs_new_view" },
      { id: "future_demand_forecast", title: "Previsão de demanda", availability: "needs_new_view" },
      { id: "future_seller_commission", title: "Comissão por vendedor", availability: "needs_new_view" },
      { id: "future_profitability_by_seller", title: "Rentabilidade por vendedor", availability: "needs_new_view" },
      { id: "future_profitability_by_customer", title: "Rentabilidade por cliente", availability: "needs_new_view" },
      { id: "future_profitability_by_product", title: "Rentabilidade por produto", availability: "needs_new_view" },
      { id: "future_customer_default", title: "Inadimplência por cliente", availability: "needs_new_view" },
      { id: "future_avg_payment_term", title: "Prazo médio de pagamento", availability: "needs_new_view" },
      { id: "future_customer_ltv", title: "Lifetime Value do cliente", availability: "needs_new_view" },
      { id: "future_customer_churn", title: "Churn de clientes", availability: "needs_new_view" },
      { id: "future_customer_repurchase", title: "Recompra por cliente", availability: "needs_new_view" },
      { id: "future_avg_purchase_frequency", title: "Frequência média de compra", availability: "needs_new_view" },
      { id: "future_real_cross_sell_upsell", title: "Cross-sell e up-sell real", availability: "needs_new_view" },
      { id: "future_marketing_campaign_sales", title: "Campanha de marketing x venda", availability: "needs_new_view" },
    ],
  },
  {
    id: "kpis",
    name: "KPIs essenciais",
    description: "Cards principais para abrir a tela com leitura executiva imediata.",
    plannedCount: 25,
    availableNowCount: 22,
    needsNewViewCount: 0,
    highlights: [
      { id: "kpi_total_budget_amount", title: "Valor total orçado", availability: "available_now" },
      { id: "kpi_budget_count", title: "Quantidade de orçamentos", availability: "available_now" },
      { id: "kpi_avg_ticket", title: "Ticket médio", availability: "available_now" },
      { id: "kpi_conversion_rate", title: "Taxa de conversão", availability: "needs_mapping" },
      { id: "kpi_open_amount", title: "Valor em aberto", availability: "available_now" },
      { id: "kpi_approved_amount", title: "Valor aprovado", availability: "available_now" },
      { id: "kpi_lost_amount", title: "Valor perdido", availability: "available_now" },
      { id: "kpi_best_seller", title: "Melhor vendedor", availability: "available_now" },
      { id: "kpi_best_customer", title: "Melhor cliente", availability: "available_now" },
      { id: "kpi_best_product", title: "Melhor produto", availability: "available_now" },
      { id: "kpi_best_city", title: "Melhor cidade", availability: "available_now" },
      { id: "kpi_best_uf", title: "Melhor UF", availability: "available_now" },
      { id: "kpi_best_origin", title: "Melhor origem", availability: "available_now" },
      { id: "kpi_highest_discount", title: "Maior desconto concedido", availability: "available_now" },
      { id: "kpi_avg_discount", title: "Desconto médio", availability: "available_now" },
      { id: "kpi_avg_markup", title: "Markup médio", availability: "available_now" },
      { id: "kpi_avg_freight", title: "Frete médio", availability: "available_now" },
      { id: "kpi_most_quoted_product", title: "Produto mais orçado", availability: "available_now" },
      { id: "kpi_highest_potential_customer", title: "Cliente com maior potencial", availability: "available_now" },
      { id: "kpi_seller_highest_growth", title: "Vendedor com maior crescimento", availability: "available_now" },
      { id: "kpi_seller_highest_drop", title: "Vendedor com maior queda", availability: "available_now" },
      { id: "kpi_product_highest_growth", title: "Produto com maior crescimento", availability: "available_now" },
      { id: "kpi_product_highest_drop", title: "Produto com maior queda", availability: "available_now" },
      { id: "kpi_channel_highest_conversion", title: "Canal com maior conversão", availability: "needs_mapping" },
      { id: "kpi_channel_lowest_conversion", title: "Canal com menor conversão", availability: "needs_mapping" },
    ],
  },
];

export const salesBudgetTotals = salesBudgetCatalog.reduce(
  (acc, category) => {
    acc.plannedCharts += category.plannedCount;
    acc.availableNowCharts += category.availableNowCount;
    acc.needsNewViewCharts += category.needsNewViewCount;
    return acc;
  },
  {
    plannedCharts: 0,
    availableNowCharts: 0,
    needsNewViewCharts: 0,
  }
);
